# Generated by Django 5.0.4 on 2024-10-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetectorApp', '0002_userimage_was_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processeduserimage',
            name='processed_image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
