# Generated by Django 5.0.4 on 2024-10-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetectorApp', '0006_alter_processeduserimage_processed_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentuser',
            name='current_user',
            field=models.TextField(default='Вход не выполнен'),
        ),
    ]
